[project]
name = "fastapi-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "gunicorn>=23.0.0",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
]
